# Generated by Django 3.2.6 on 2021-08-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='frindly_name',
            new_name='friendly_name',
        ),
    ]
